apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-sa
  name: pod-with-sa
spec:
  containers:
  - image: nginx
    name: pod-with-sa
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: epatel-service-account
status: {}
