apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: epatel-use-var
  name: epatel-use-var
spec:
  containers:
  - image: nginx
    name: epatel-use-var
    resources: {}
    env: 
    - name: APP_NAME
      valueFrom: 
        configMapKeyRef:
         name: epatel-configmap
         key: APP_NAME
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
