apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: epatel-use-env
  name: epatel-use-env
spec:
  containers:
  - image: nginx
    name: epatel-use-env
    envFrom: 
    - configMapRef:
        name: epatel-configmap
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
