apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: epatel-voting-app
spec:
  type: ClusterIP
  selector:
    name: postgres-pod
    app: epatel-voting-app
  ports:
  - port: 5432
    targetPort: 5432
