apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    name: result-app-service
    app: epatel-voting-app
spec:
  type: NodePort
  selector:
    name: result-app-pod
    app: epatel-voting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
