apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-user
  name: pod-with-user
spec:
  securityContext: 
    runAsUser: 1001 
  containers:
  - image: alpine
    name: pod-with-user
    command: 
    - "sleep"
    - "400"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
