apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis-deploy
  labels:
    name: redis-deploy
    app: epatel-voting-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis-pod
        app: epatel-voting-app
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
  selector:
    matchLabels:
      name: redis-pod
      app: epatel-voting-app