apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: epatel-voting-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres-pod
        app: epatel-voting-app
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres" 
  selector:
    matchLabels:
      name: postgres-pod
      app: epatel-voting-app
