apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-app-deploy
  labels:
    name: worker-app-deploy
    app: epatel-voting-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: worker-app-pod
        app: epatel-voting-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v2
  selector:
    matchLabels:
      name: worker-app-pod
      app: epatel-voting-app