apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: epatel-secret-use-env
  name: epatel-secret-use-env
spec:
  containers:
  - image: nginx
    name: epatel-secret-use-env
    resources: {}
    envFrom:
    - secretRef:
        name: epatel-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
