apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: epatel-secret-use-var
  name: epatel-secret-use-var
spec:
  containers:
  - image: nginx
    name: epatel-secret-use-var
    env: 
    - name: SECRET_APP_NAME
      valueFrom:
        secretKeyRef:
          name: epatel-secret
          key: SECRET_APP_NAME
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
